AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fast-food-lambda

  Sample SAM Template for fast-food-lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  FastFoodLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FastFoodLambda
      Handler: fastfood.App::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Role: arn:aws:iam::566814225519:role/LabRole  # replace with your AWS account ID
      Environment:
        Variables:
          userPoolId: us-east-1_VQkQuLCzq
          appClientId: 7m3o7thnihntm9asogh27edq82
          clientSecret: clo45u50kt7v75bvkkjuq4utpcq5keuebk2hd35via6v6mjm568
          defaultUser: Admin
          defaultPassword: Admin123
      Events:
        FastFood:
          Type: Api
          Properties:
            Path: /identificaliente
            Method: get

Outputs:
  FastFoodApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/identificaliente/"
  FastFoodLambda:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FastFoodLambda.Arn