AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fast-food-lambda

  Sample SAM Template for fast-food-lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  FastFoodLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FastFoodLambda
      Handler: fastfood.App::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Role: arn:aws:iam::631818169384:role/LabRole  # replace with your AWS account ID
      Environment:
        Variables:
          userPoolId: us-east-1_Swqd4YA5h
          appClientId: 6dm3je7bc7thsseeh0rc32vohi
          clientSecret: 1olarkpedcl0u37nt7pklurh5jkjbqvid698q20tluijr7ti77q5
          defaultUser: Admin
          defaultPassword: Admin123
      Events:
        FastFood:
          Type: Api
          Properties:
            Path: /identificaliente
            Method: get

Outputs:
  FastFoodApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FastFoodLambda:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FastFoodLambda.Arn