AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fast-food-lambda

  Sample SAM Template for fast-food-lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  FastFoodLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FastFoodLambda
      Handler: fastfood.App::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole  # replace with your AWS account ID
      Environment:
        Variables:
          userPoolId: ${{ secrets.COGNITO_USER_POOL_ID }}
          appClientId:  ${{ secrets.APP_CLIENT_ID }}
          clientSecret: ${{ secrets.AAP_CLIENT_SECRET }}
          defaultUser: Admin
          defaultPassword: Admin123
      Events:
        FastFood:
          Type: Api
          Properties:
            Path: /identificaliente
            Method: get

Outputs:
  FastFoodApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/identificaliente/"
  FastFoodLambda:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FastFoodLambda.Arn